# Markdown Configuration
[md]
badges_tech_stack_text = "Built with the tools and technologies:"
badges_tech_stack = """{badges_tech_stack}"""
github_stats = """
![GitHub Forks](https://img.shields.io/github/forks/{full_name}?style={badge_style}&logo=github&logoColor=white&color={badge_color})
![GitHub Stars](https://img.shields.io/github/stars/{full_name}?style={badge_style}&logo=github&logoColor=white&color={badge_color})
![GitHub Watchers](https://img.shields.io/github/watchers/{full_name}?style={badge_style}&logo=github&logoColor=white&color={badge_color})
![GitHub Issues](https://img.shields.io/github/issues/{full_name}?style={badge_style}&logo=github&logoColor=white&color={badge_color})
![GitHub Pull Requests](https://img.shields.io/github/issues-pr/{full_name}?style={badge_style}&logo=github&logoColor=white&color={badge_color})
![GitHub Release](https://img.shields.io/github/v/release/{full_name}?style={badge_style}&logo=github&logoColor=white&color={badge_color})
"""

shieldsio_icons = """
<img src="https://img.shields.io/{host}/license/{full_name}?style={badge_style}&logo=opensourceinitiative&logoColor=white&color={badge_color}" alt="license">
\t<img src="https://img.shields.io/{host}/last-commit/{full_name}?style={badge_style}&logo=git&logoColor=white&color={badge_color}" alt="last-commit">
\t<img src="https://img.shields.io/{host}/languages/top/{full_name}?style={badge_style}&color={badge_color}" alt="repo-top-language">
\t<img src="https://img.shields.io/{host}/languages/count/{full_name}?style={badge_style}&color={badge_color}" alt="repo-language-count">
"""

skill_icons = """<a href="https://skillicons.dev">\n\t\t<img src="{}">\n\t</a>"""

overview = """
## Overview

{0}

---
"""

table_of_contents = """

## Table of contents

- [Core features](#core-features)
- [Installation](#installation)
- [Examples](#examples)
- [Getting started](#getting-started)
- [Documentation](#documentation)
- [License](#license)
- [Acknowledgments](#acknowledgments)
- [Contacts](#contacts)
- [Citation](#citation)

---
"""

core_features = """
## Core features

{0}
"""

quickstart = """
## Installation

##### Build from Source

1. Clone the {repo_name} repository:
```sh
❯ git clone {repo_url}
```

2. Navigate to the project directory:
```sh
❯ cd {repo_name}
```

3. Install the project dependencies:

{install_commands}

---

## Examples

Describe examples how it should work and should be used. Images, GIFs and code cells are welcome.

---

## Getting Started

##### Usage

Run {repo_name} using the following command:

{usage_commands}

##### Testing

Execute the test suite using the following command:

{test_commands}

---
"""


# -- Contributing Section -----------------------------------------------------------


contribute = """
---
## Documentation

A detailed {repo_name} description is available in ...

---

## Contributing

- **[Join the Discussions](https://{host_domain}/{full_name}/discussions)**: Share your insights, provide feedback, or ask questions.
- **[Report Issues](https://{host_domain}/{full_name}/issues)**: Submit bugs found or log feature requests for the `{repo_name}` project.
- **[Submit Pull Requests](https://{host_domain}/{full_name}/blob/main/CONTRIBUTING.md)**: Review open PRs, and submit your own PRs.

<details closed>
<summary>Contributing Guidelines</summary>

1. **Fork the Repository**: start by forking the project repository to your {host} account.
2. **Clone Locally**: clone the forked repository to your local machine using a git client.
   ```sh
   git clone {repo_url}
   ```
3. **Create a New Branch**: always work on a new branch, giving it a descriptive name.
   ```sh
   git checkout -b new-feature-x
   ```
4. **Make Your Changes**: develop and test your changes locally.
5. **Commit Your Changes**: commit with a clear message describing your updates.
   ```sh
   git commit -m 'Implemented new feature x.'
   ```
6. **Push to {host}**: push the changes to your forked repository.
   ```sh
   git push origin new-feature-x
   ```
7. **Submit a Pull Request**: create a PR against the original project repository. Clearly describe the changes and their motivations.
8. **Review**: once your PR is reviewed and approved, it will be merged into the main branch. Congratulations on your contribution!
</details>

<details closed>
<summary>Contributor Graph</summary>
<br>
<p align="left">
   <a href="https://{host_domain}{{/{full_name}/}}graphs/contributors">
      <img src="https://contrib.rocks/image?repo={full_name}">
   </a>
</p>
</details>

---

## License

This project is protected under the [SELECT-A-LICENSE](https://choosealicense.com/licenses) License. For more details, refer to the [LICENSE](https://choosealicense.com/licenses/) file.

---

## Acknowledgments

- List any resources, contributors, inspiration, etc. here.

---

## Contacts

Your contacts. For example:

- [Telegram channel](https://t.me/) answering questions about your project
- [VK group](<https://vk.com/>) your VK group
- etc.

---

## Citation

...

"""

contributing = """
## Contributing

- **[Join the Discussions](https://{host_domain}/{full_name}/discussions)**: Share your insights, provide feedback, or ask questions.
- **[Report Issues](https://{host_domain}/{full_name}/issues)**: Submit bugs found or log feature requests for the `{repo_name}` project.
- **[Submit Pull Requests](https://{host_domain}/{full_name}/blob/main/CONTRIBUTING.md)**: Review open PRs, and submit your own PRs.

---
"""

contributing_guidelines = """
<details open><summary>Contributing Guidelines</summary><br>

1. **Fork the Repository**: Start by forking the project repository to your {host} account.
2. **Clone Locally**: Clone the forked repository to your local machine using a git client.
   ```sh
   git clone {repo_url}
   ```
3. **Create a New Branch**: Always work on a new branch, giving it a descriptive name.
   ```sh
   git checkout -b new-feature-x
   ```
4. **Make Changes**: Develop and test your changes locally.
5. **Commit Changes**: Commit with a clear message describing your updates.
   ```sh
   git commit -m 'Implemented new feature x.'
   ```
6. **Push to {host}**: Push the changes to your forked repository.
   ```sh
   git push origin new-feature-x
   ```
7. **Submit a Pull Request**: Create a PR against the original project repository. Clearly describe the changes and their motivations.
8. **Review**: Once your PR is reviewed and approved, it will be merged into the main branch. Congratulations on your contribution!

</details>
"""

contributor_graph = """
<p align="{align}">
  <a href="https://{host_domain}{/{full_name}/}graphs/contributors">
    <img src="https://contrib.rocks/image?repo={full_name}" />
  </a>
</p>
"""


# -- Contact Section -----------------------------------------------------------


contact = """
<p align="center">
  <sub>
    For {name} issues and feature requests please visit the <a href="https://{host_domain}/{full_name}/issues">issues</a> page, or feel free to start a <a href="https://github.com/eli64s/readme-ai/discussions">discussion!</a>
  </sub><br>
</p>
<div align="center">
  <a href="https://github.com/eli64s"><img src="https://github.com/ultralytics/assets/raw/main/social/logo-social-github.png" width="3%" alt="eli64s GitHub"></a>
  <img src="https://github.com/ultralytics/assets/raw/main/social/logo-transparent.png" width="3%" alt="space">
  <a href="https://www.linkedin.com/company/ultralytics/"><img src="https://github.com/ultralytics/assets/raw/main/social/logo-social-linkedin.png" width="3%" alt="Ultralytics LinkedIn"></a>
  <img src="https://github.com/ultralytics/assets/raw/main/social/logo-transparent.png" width="3%" alt="space">
  <a href="https://twitter.com/ultralytics"><img src="https://github.com/ultralytics/assets/raw/main/social/logo-social-twitter.png" width="3%" alt="Ultralytics Twitter"></a>
  <img src="https://github.com/ultralytics/assets/raw/main/social/logo-transparent.png" width="3%" alt="space">
</div>
"""

# -- API Documentation Section -----------------------------------------------------------


api_docs = """
### API Documentation

The project API documentation is available at: [API Documentation]({api_url}).

---
"""

env_variables = """
### Environment Variables

To run this project, you will need to add the following environment variables to your environment:

{env_variables}

---
"""

cli_docs = """
### Command-Line Interface

The project supports the following command-line interface options:

```sh
❯ {cli_command}
```

---
"""

test_framework = """
### Testing

This project uses [{test_framework}]() for testing. Execute the test suite using the following command:

```sh
❯ {test_command}
```

---
"""

signature = """
<p align="center">
  <sub>Generated by <a href="https://github.com/eli64s/readme-ai">readme-ai</a></sub>
</p>
<p align="center">
  <a href="https://github.com/eli64s/readme-ai">
    <img src="https://img.shields.io/badge/readme--ai-DDDDDD?style=flat&logo=ReadMe&logoColor=blueviolet" alt="readme-ai">
  </a>
</p>
"""