# Git Repository Settings
[git]
repository = "https://github.com/aimclub/OSA"
no_fork = false
no_pull_request = false

# Language Model API Settings
[llm]
api = "itmo"
rate_limit = 10
base_url = "https://api.openai.com/v1"
encoder = "cl100k_base"
host_name = "https://api.openai.com/v1"
localhost = "http://localhost:11434/"
model = "gpt-3.5-turbo"
path = "generate"
temperature = 0.05
max_tokens = 4096
context_window = 16385
top_p = 0.95
max_retries = 3
allowed_providers = ["google-vertex", "azure"]

# General CLI-related defaults
[general]
mode = "auto"
web_mode = false
# output = ""
# branch = ""
# attachment = ""
translate_dirs = false
translate_readme = []
# convert_notebooks = []
delete_dir = false
# ensure_license = ""
community_docs = false
docstring = false
report = false
readme = false
refine_readme = false
requirements = false
organize = false
about = false

#Workflow Settings
[workflows]
generate_workflows = false
include_tests = true
include_black = true
include_pep8 = true
include_autopep8 = false
include_fix_pep8 = false
include_pypi = false
python_versions = ["3.8", "3.9", "3.10"]
pep8_tool = "flake8" # "flake8" or "pylint"
use_poetry = false
branches = []
codecov_token = false
include_codecov = true