# Git Repository Settings
[git]
repository = "https://github.com/aimclub/OSA"

# Language Model API Settings
[llm]
api = "openai"
url = "https://api.openai.com/v1"
context_window = 4096
encoder = "cl100k_base"
host_name = "https://api.openai.com/v1"
localhost = "http://localhost:11434/"
model = "gpt-3.5-turbo"
path = "generate"
temperature = 0.05
tokens = 4096
top_p = 0.95

# GitHub Actions Workflow Settings
[workflows]
generate_workflows = false
output_dir = ".github/workflows"
include_tests = true
include_black = true
include_pep8 = true
include_autopep8 = false
include_fix_pep8 = false
include_pypi = false
python_versions = ["3.8", "3.9", "3.10"]
pep8_tool = "flake8" # "flake8" or "pylint"
use_poetry = false
branches = []
codecov_token = false
include_codecov = true